Pull and Push of Line and Node Constraints
BHoM/RFEM6_Toolkit pull request #29
Opened 2023-08-02 10:06 UTC by Arne-Martensen

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #

### Test files

### Changelog

### Additional comments

2023-09-07 09:29 UTC, staintono reviewed
Using the test script provided I tried to push nodal supports. This did not work and produced the following error: 
1. This component failed to run properly.
- Error: Object reference not set to an instance of an object.
- Occured in  BH.Adapter.RFEM6.RFEM6Adapter.Disconnect()
     called from BH.Adapter.RFEM6.RFEM6Adapter.Push(IEnumerable`1 objects, String tag, PushType pushType, ActionConfig actionConfig)
- Are you sure you have the correct type of inputs? Check their description for more details.

The code was not reviewed.

2023-09-07 14:39 UTC, staintono requested changes
Tested by creating a rectangular panel and extract its edges to use as line supports. The surface and the line support types are pushed correctly, however the lines/panel edges do not have the line support types associated with them.

2023-09-08 06:58 UTC, Arne-Martensen commented
> Tested by creating a rectangular panel and extract its edges to use as line supports. The surface and the line support types are pushed correctly, however the lines/panel edges do not have the line support types associated with them. Using the same process but with nodes, the node supports are correctly pushed and assigned.

In your script, I noticed you're trying to push the same edge twice: once as part of the panel and once separately, but with constraints. When creating a panel using outlines (not edges), it's important to know that the panel component internally defines edges based on your input curve. So, to the computer, it appears you're pushing the same edge twice: once with constraints and once without. This causes a conflict, and the computer has to choose one. In your case, it seems the edge for support was ignored when creating the geometry, but used only to define LineSupport. Meanwhile, the panel edge defined the geometry. This conflict results in a LineSupport that isn't aware of its connection to the panel.

I'll have another look but it is important to point out that this approach may increase computational load, as it requires looping and comparing edges for equality. 

A quick solution to your issue is to define the panel using edges that already have the constraints attached.

2023-09-19 10:22 UTC, staintono submitted a review, later dismissed
The PR was reviewed using the provided test scripts as well as some user created geometries. The following elements were tested successfully with both pushing and pulling: Nodal and Line Supports with straight lines, polylines and arcs, Bar Releases. Line supports that coincide with Surface outlines could only be pushed when using edges to define the surface. Arcs are now pushed without the helper nodes and now only contain the minimum needed to define the arc. 
When pulling supports with spring stiffnesses were pulled as Free supports rather than fixed, however due to the fact that the toolkit currently does not support spring stiffnesses this will be raised as a separate issue. 
The Code was not reviewed.

2023-10-09 08:49 UTC, staintono submitted a review, later dismissed
The PR was tested using the provided test scripts as well as user created models. The following elements were tested and can be successfully pushed and pulled: Nodal Supports, Line Supports, Bar Hinges. The Line supports can only be pushed when pushed as part of an Edge that defines a panel. Arcs can now be pushed without the helper nodes being present after the push. The code was not checked

2023-10-09 09:01 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check required

2023-10-09 09:04 UTC, FraserGreenroyd requested changes
Please resolve the compliance issues highlighted by the bot as well.

2023-10-09 09:04 UTC, FraserGreenroyd commented on RFEM6_Adapter/CRUD/Create/Node.cs
> +
```suggestion
            if (input.Equals(double.PositiveInfinity))
                return DOFType.Fixed;
            else
                return DOFType.Free;
```

2023-10-09 09:04 UTC, FraserGreenroyd commented on RFEM6_Adapter/CRUD/Create/Node.cs
> +            if (!tranlate(rfSupport.spring_x).Equals(bhConstraint.TranslationX)) { return false; }
Please put all commands from an `if` onto its own line - no need for brackets if only a single line return is used.

2023-10-09 09:24 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-10-09 09:27 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-10-09 09:32 UTC, FraserGreenroyd commented
@BHoMBot check serialisation
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check null-handling

2023-10-09 09:40 UTC, FraserGreenroyd approved these changes
Approving based on [this review](https://github.com/BHoM/RFEM6_Toolkit/pull/29#pullrequestreview-1663984578) as remaining commits have been for compliance and rebasing.

2023-10-09 09:41 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 17520982879

2023-10-09 10:02 UTC, merged